export const CATEGORY_EMBROIDERY = "Mašinski vez"
export const CATEGORY_DTF = "DTF"
export const CATEGORY_OTHER = "Razno"

export const portfolioCategories = [CATEGORY_EMBROIDERY, CATEGORY_DTF, CATEGORY_OTHER] as const

export interface PortfolioItem {
  id: number
  category: string[]
  image_alt_text: string
  title: string
  context: string
  technique: string
  image: string
  width: number
  height: number
}

export const portfolioItems: PortfolioItem[] = [
  {
    id: 1,
    category: [CATEGORY_EMBROIDERY],
    image_alt_text: "Mašinski vez na peškirima i posteljini za hotele, ADD VERT, Petrovac na Mlavi",
    title: "Peškiri i posteljina za hotele",
    context: "Mašinski vez logotipa i monograma na hotelskom tekstilu za ujednačen i profesionalan izgled soba.",
    technique: "Mašinski vez",
    image: "/images/galerija/masinski-vez/masinski-vez-peskir-posteljina-hoteli.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 2,
    category: [CATEGORY_EMBROIDERY],
    image_alt_text: "Mašinski vez na peškiru za krštenje, ADD VERT",
    title: "Peškir za krštenje",
    context: "Personalizovani peškir sa vezom za krštenje.",
    technique: "Mašinski vez",
    image: "/images/galerija/masinski-vez/masinski-vez-peskir-vencanje.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 3,
    category: [CATEGORY_EMBROIDERY],
    image_alt_text: "Mašinski vez na duksericama sa amblemom, ADD VERT",
    title: "Dukserice sa amblemom",
    context: "Vez na duksericama za klubove, timove i promotivnu garderobu.",
    technique: "Mašinski vez",
    image: "/images/galerija/masinski-vez/masinski-vez-dukserice-klub.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 4,
    category: [CATEGORY_EMBROIDERY],
    image_alt_text: "Mašinski vez na radnim prslucima, ADD VERT",
    title: "Radni prsluci",
    context: "Brendirani prsluci za radne timove, servise i terensko osoblje.",
    technique: "Mašinski vez",
    image: "/images/galerija/masinski-vez/masinski-vez-radni-prsluci.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 5,
    category: [CATEGORY_EMBROIDERY],
    image_alt_text: "Mašinski vez amblema moto kluba, ADD VERT",
    title: "Moto klub, amblem",
    context: "Prepoznatljiv amblem moto kluba na garderobi za članove i događaje.",
    technique: "Mašinski vez",
    image: "/images/galerija/masinski-vez/masinski-vez-moto-klub-amblem.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 6,
    category: [CATEGORY_EMBROIDERY],
    image_alt_text: "Mašinski vez amblema za sportske klubove, ADD VERT",
    title: "Amblemi za sportske klubove",
    context: "Vezeni amblemi i oznake za sportske klubove.",
    technique: "Mašinski vez",
    image: "/images/galerija/masinski-vez/masinski-vez-amblemi-udruzenja.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 7,
    category: [CATEGORY_EMBROIDERY],
    image_alt_text: "Mašinski vez logotipa na kačketima, ADD VERT",
    title: "Kačketi sa logotipom",
    context: "Vez logotipa na kačketima za firme, klubove i promo timove.",
    technique: "Mašinski vez",
    image: "/images/galerija/masinski-vez/masinski-vez-kacketi-logo.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 8,
    category: [CATEGORY_EMBROIDERY],
    image_alt_text: "Mašinski vez na softshell jakni, ADD VERT",
    title: "Softshell jakna",
    context: "Diskretan ili uočljiv vez na softshell jaknama za korporativnu i radnu garderobu.",
    technique: "Mašinski vez",
    image: "/images/galerija/masinski-vez/masinski-vez-softshell-jakna.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 9,
    category: [CATEGORY_EMBROIDERY],
    image_alt_text: "Mat mašinski vez na organic cotton majicama, ADD VERT",
    title: "Organic cotton majice",
    context: "Mat plavi vez na premium pamučnim majicama za brendove koji traže čist završetak.",
    technique: "Mašinski vez",
    image: "/images/galerija/masinski-vez/masinski-vez-organic-cotton-majice.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 10,
    category: [CATEGORY_EMBROIDERY],
    image_alt_text: "Mašinski vez na radnim jaknama, ADD VERT",
    title: "Radne jakne",
    context: "Vez na radnim jaknama za servise, proizvodnju i terenske timove.",
    technique: "Mašinski vez",
    image: "/images/galerija/masinski-vez/masinski-vez-radne-jakne.webp",
    width: 1024,
    height: 1024,
  },
  {
    id: 11,
    category: [CATEGORY_EMBROIDERY],
    image_alt_text: "Mašinski vez na softshell jakni za udruženje, ADD VERT",
    title: "Softshell jakna za udruženje",
    context: "Brendiranje softshell jakni za članove udruženja i timove na terenu.",
    technique: "Mašinski vez",
    image: "/images/galerija/masinski-vez/masinski-vez-softshell-jakna-2.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 12,
    category: [CATEGORY_EMBROIDERY],
    image_alt_text: "Mašinski vez na softshell prslucima, ADD VERT",
    title: "Softshell prsluci",
    context: "Vez na prslucima za ugostiteljstvo, recepciju i lager timove.",
    technique: "Mašinski vez",
    image: "/images/galerija/masinski-vez/masinski-vez-softshell-prsluci.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 13,
    category: [CATEGORY_EMBROIDERY],
    image_alt_text: "Mašinski vez na flisu i kapama, ADD VERT",
    title: "Flis i kape",
    context: "Vez na flis jaknama i zimskim kapama za sezonu i outdoor timove.",
    technique: "Mašinski vez",
    image: "/images/galerija/masinski-vez/masinski-vez-flis-kape.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 14,
    category: [CATEGORY_EMBROIDERY],
    image_alt_text: "Mašinski vez na poslovnim košuljama, ADD VERT",
    title: "Poslovne košulje",
    context: "Elegantan vez na košuljama za recepciju, prodaju i korporativni tim.",
    technique: "Mašinski vez",
    image: "/images/galerija/masinski-vez/masinski-vez-kosulje.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 15,
    category: [CATEGORY_EMBROIDERY],
    image_alt_text: "Mašinski vez na raznim tekstilnim artiklima, ADD VERT",
    title: "Razni tekstilni artikli",
    context: "Primeri veza na različitim materijalima i proizvodima po narudžbi.",
    technique: "Mašinski vez",
    image: "/images/galerija/masinski-vez/masinski-vez-razni-artikli.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 16,
    category: [CATEGORY_EMBROIDERY],
    image_alt_text: "Mašinski vez na zimskim kapama, ADD VERT",
    title: "Zimske kape",
    context: "Vez na zimskim kapama za radne timove, klubove i promo događaje.",
    technique: "Mašinski vez",
    image: "/images/galerija/masinski-vez/masinski-vez-zimske-kape.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 17,
    category: [CATEGORY_DTF],
    image_alt_text: "DTF štampa na teget majicama, ADD VERT, Petrovac na Mlavi",
    title: "Teget majice, DTF",
    context: "Štampa na teget majicama za timove, promocije i događaje.",
    technique: "DTF štampa",
    image: "/images/galerija/dtf/dtf-stampa-teget-majice.webp",
    width: 1024,
    height: 1024,
  },
  {
    id: 18,
    category: [CATEGORY_DTF],
    image_alt_text: "DTF štampa na duksericama, ADD VERT",
    title: "Dukserice, DTF štampa",
    context: "Puna šarena štampa na duksericama za klubove i brendove.",
    technique: "DTF štampa",
    image: "/images/galerija/dtf/dtf-stampa-dukserice.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 19,
    category: [CATEGORY_DTF],
    image_alt_text: "DTF štampa na majicama, ADD VERT",
    title: "Majice, DTF štampa",
    context: "DTF štampa na majicama za kampanje, događaje i promo timove.",
    technique: "DTF štampa",
    image: "/images/galerija/dtf/dtf-stampa-majice.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 20,
    category: [CATEGORY_DTF],
    image_alt_text: "DTF štampa na premium majicama, ADD VERT",
    title: "Premium majice",
    context: "Kvalitetna DTF štampa na premium majicama za brendove koji traže bolji završetak.",
    technique: "DTF štampa",
    image: "/images/galerija/dtf/dtf-stampa-premium-majice.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 21,
    category: [CATEGORY_DTF],
    image_alt_text: "DTF štampa preslikačima na duplim presama, ADD VERT",
    title: "DTF, duple prese",
    context: "Proizvodnja DTF preslikača i transfera za veće serije i složenije motive.",
    technique: "DTF štampa",
    image: "/images/galerija/dtf/dtf-stampa-duple-prese.webp",
    width: 1024,
    height: 1024,
  },
  {
    id: 22,
    category: [CATEGORY_OTHER],
    image_alt_text: "3D stikeri za brendiranje objekata, ADD VERT",
    title: "3D stikeri",
    context: "Proizvodnja i montaža 3D stikera za izloge, objekte i promotivne površine.",
    technique: "3D stikeri",
    image: "/images/galerija/razno/razno-3d-stikeri.webp",
    width: 1024,
    height: 1024,
  },
  {
    id: 23,
    category: [CATEGORY_OTHER],
    image_alt_text: "Bilbord reklama, ADD VERT štamparija",
    title: "Bilbord reklama",
    context: "Štampa i postavljanje bilbord reklama za lokalne i regionalne kampanje.",
    technique: "Veliki format",
    image: "/images/galerija/razno/razno-bilbord-reklama.webp",
    width: 1024,
    height: 1024,
  },
  {
    id: 24,
    category: [CATEGORY_OTHER],
    image_alt_text: "Brendiranje izloga PVC folijom, ADD VERT",
    title: "Brendiranje izloga",
    context: "PVC folije i grafike za izloge prodavnica, kancelarija i uslužnih objekata.",
    technique: "Brendiranje izloga",
    image: "/images/galerija/razno/razno-brendiranje-izloga.webp",
    width: 1024,
    height: 1024,
  },
  {
    id: 25,
    category: [CATEGORY_OTHER],
    image_alt_text: "Kompletno brendiranje izloga, ADD VERT",
    title: "Izlog, kompletna grafika",
    context: "Kompletno vizuelno rešenje za izlog sa folijama i natpisima.",
    technique: "Brendiranje izloga",
    image: "/images/galerija/razno/razno-brendiranje-izloga-2.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 26,
    category: [CATEGORY_OTHER],
    image_alt_text: "Brendiranje vozila folijom, ADD VERT",
    title: "Brendiranje vozila",
    context: "Folije i grafike na vozilima za firme, servise i dostavu.",
    technique: "Brendiranje vozila",
    image: "/images/galerija/razno/razno-brendiranje-vozila.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 27,
    category: [CATEGORY_OTHER],
    image_alt_text: "Kompletno brendiranje pekare, ADD VERT",
    title: "Brendiranje pekare",
    context: "Kompletno brendiranje pekare: izlog, unutrašnjost i promotivni elementi.",
    technique: "Brendiranje objekta",
    image: "/images/galerija/razno/razno-brendiranje-pekara.webp",
    width: 1024,
    height: 1024,
  },
  {
    id: 28,
    category: [CATEGORY_OTHER],
    image_alt_text: "Montaža reklame na objektu, ADD VERT",
    title: "Montaža reklame",
    context: "Montaža reklamnih elemenata na objektima i poslovnim prostorima.",
    technique: "Montaža reklame",
    image: "/images/galerija/razno/razno-montaza-reklame.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 29,
    category: [CATEGORY_OTHER],
    image_alt_text: "Promotivni privesci, ADD VERT",
    title: "Privesci i promo artikli",
    context: "Personalizovani privesci i sitni promotivni predmeti za događaje i poklone.",
    technique: "Promo artikli",
    image: "/images/galerija/razno/razno-privesci-promo.webp",
    width: 1024,
    height: 1024,
  },
  {
    id: 30,
    category: [CATEGORY_OTHER],
    image_alt_text: "Svetleća reklama i 3D slova, ADD VERT",
    title: "Svetleća reklama",
    context: "3D svetleća slova i reklame za istaknutu vidljivost objekta.",
    technique: "Svetleća reklama",
    image: "/images/galerija/razno/razno-svetleca-reklama.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 31,
    category: [CATEGORY_OTHER],
    image_alt_text: "UV štampa na upaljačima, ADD VERT",
    title: "UV štampa na upaljačima",
    context: "UV štampa na upaljačima i sitnim promo predmetima za poklon programe.",
    technique: "UV štampa",
    image: "/images/galerija/razno/razno-uv-stampa-upaljaci.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 32,
    category: [CATEGORY_OTHER],
    image_alt_text: "UV štampa na olovkama, upaljačima i privescima, ADD VERT",
    title: "UV štampa, promo set",
    context: "Olovke, upaljači i privesci sa brendiranjem za promocije i događaje.",
    technique: "UV štampa",
    image: "/images/galerija/razno/razno-uv-stampa-promo-set.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 33,
    category: [CATEGORY_OTHER],
    image_alt_text: "Vinil reklama na belom foreksu, ADD VERT",
    title: "Vinil na foreksu",
    context: "Vinil reklama na belom foreksu za unutrašnje i spoljašnje oznake.",
    technique: "Vinil / foreks",
    image: "/images/galerija/razno/razno-vinil-foreks-reklama.webp",
    width: 1024,
    height: 1024,
  },
  {
    id: 34,
    category: [CATEGORY_OTHER],
    image_alt_text: "Štampane vizit karte u boji, ADD VERT",
    title: "Vizit karte, color",
    context: "Štampa vizit karti u boji za firme i preduzetnike.",
    technique: "Štampa vizit karti",
    image: "/images/galerija/razno/razno-vizit-karte-color.webp",
    width: 1600,
    height: 1600,
  },
  {
    id: 35,
    category: [CATEGORY_OTHER],
    image_alt_text: "Premium vizit karte sa zlatnim štampom, ADD VERT",
    title: "Vizit karte, gold",
    context: "Premium vizit karte sa zlatnim detaljima za reprezentativan prvi utisak.",
    technique: "Štampa vizit karti",
    image: "/images/galerija/razno/razno-vizit-karte-gold.webp",
    width: 900,
    height: 900,
  }
]
